import casque from "@/assets/p-casque.jpg";
import montre from "@/assets/p-montre.jpg";
import enceinte from "@/assets/p-enceinte.jpg";
import lampe from "@/assets/p-lampe.jpg";
import tapis from "@/assets/p-tapis.jpg";
import sac from "@/assets/p-sac.jpg";
import cheche from "@/assets/p-cheche.jpg";
import argan from "@/assets/p-argan.jpg";
export const categories = [
    { id: "c1", slug: "electronique", name: "Électronique", description: "Audio, montres et objets connectés" },
    { id: "c2", slug: "maison", name: "Maison", description: "Décoration et artisanat pour la maison" },
    { id: "c3", slug: "mode", name: "Mode", description: "Cuir, lin et accessoires" },
    { id: "c4", slug: "beaute", name: "Beauté", description: "Soins naturels et huiles bio" },
];
export const demoProducts = [
    {
        id: "demo-p1",
        slug: "casque-audio-pro",
        name: "Casque audio Pro",
        description: "Casque sans fil avec réduction de bruit, autonomie longue durée et son immersif.",
        price: 279.9,
        compareAtPrice: 329.9,
        categoryId: "c1",
        stock: 18,
        images: [casque, casque],
        rating: 4.8,
        featured: true,
        createdAt: "2026-07-01T09:00:00.000Z",
    },
    {
        id: "demo-p2",
        slug: "montre-connectee-lite",
        name: "Montre connectée Lite",
        description: "Montre élégante avec suivi du rythme cardiaque, notifications et résistance à l'eau.",
        price: 189,
        categoryId: "c1",
        stock: 27,
        images: [montre, montre],
        rating: 4.5,
        featured: false,
        createdAt: "2026-07-03T09:00:00.000Z",
    },
    {
        id: "demo-p3",
        slug: "enceinte-bluetooth-mini",
        name: "Enceinte Bluetooth Mini",
        description: "Enceinte compacte avec basses puissantes, connexion rapide et design portable.",
        price: 99.9,
        compareAtPrice: 119.9,
        categoryId: "c1",
        stock: 35,
        images: [enceinte, enceinte],
        rating: 4.4,
        featured: false,
        createdAt: "2026-07-05T09:00:00.000Z",
    },
];
export const demoProductCards = [
    {
        name: 'Casque audio Pro',
        price: 279.9,
        image: casque,
    },
    {
        name: 'Montre connectée Lite',
        price: 189,
        image: montre,
    },
    {
        name: 'Enceinte Bluetooth Mini',
        price: 99.9,
        image: enceinte,
    },
];
export const products = [
    {
        id: "p1",
        slug: "casque-audio-sans-fil",
        name: "Casque audio sans fil Aura",
        description: "Un casque circum-auriculaire à réduction de bruit active, 40 heures d'autonomie et coussinets en mousse à mémoire de forme. Livré avec étui rigide et câble USB-C.",
        price: 429.9,
        compareAtPrice: 529.9,
        categoryId: "c1",
        stock: 24,
        images: [casque, casque],
        rating: 4.7,
        featured: true,
        createdAt: "2026-05-02T09:00:00.000Z",
    },
    {
        id: "p2",
        slug: "montre-connectee-nova",
        name: "Montre connectée Nova",
        description: "Écran AMOLED 1,4\", suivi du sommeil et de la fréquence cardiaque, résistance à l'eau 5 ATM et bracelet milanais interchangeable.",
        price: 619,
        categoryId: "c1",
        stock: 11,
        images: [montre, montre],
        rating: 4.5,
        featured: true,
        createdAt: "2026-04-18T09:00:00.000Z",
    },
    {
        id: "p3",
        slug: "enceinte-bluetooth-mira",
        name: "Enceinte Bluetooth Mira",
        description: "Enceinte compacte en tissu recyclé, son 360°, 12 heures d'autonomie et certification IPX7 pour la plage comme pour la maison.",
        price: 189.5,
        compareAtPrice: 229,
        categoryId: "c1",
        stock: 3,
        images: [enceinte, enceinte],
        rating: 4.3,
        featured: false,
        createdAt: "2026-03-11T09:00:00.000Z",
    },
    {
        id: "p4",
        slug: "lampe-bois-olivier",
        name: "Lampe en bois d'olivier",
        description: "Pied tourné à la main dans du bois d'olivier tunisien, abat-jour en lin naturel. Chaque pièce est unique par ses veines.",
        price: 259,
        categoryId: "c2",
        stock: 15,
        images: [lampe, lampe],
        rating: 4.8,
        featured: true,
        createdAt: "2026-02-20T09:00:00.000Z",
    },
    {
        id: "p5",
        slug: "tapis-berbere-tisse-main",
        name: "Tapis berbère tissé main",
        description: "Laine vierge tissée à Kairouan selon des motifs géométriques traditionnels. Dimensions 120 × 180 cm.",
        price: 890,
        compareAtPrice: 1050,
        categoryId: "c2",
        stock: 6,
        images: [tapis, tapis],
        rating: 4.9,
        featured: true,
        createdAt: "2026-01-30T09:00:00.000Z",
    },
    {
        id: "p6",
        slug: "sac-cuir-artisanal",
        name: "Sac en cuir artisanal",
        description: "Cuir pleine fleur tanné végétalement, doublure coton, bandoulière réglable. Fabriqué dans un atelier familial à Sfax.",
        price: 349,
        categoryId: "c3",
        stock: 0,
        images: [sac, sac],
        rating: 4.6,
        featured: false,
        createdAt: "2026-01-12T09:00:00.000Z",
    },
    {
        id: "p7",
        slug: "cheche-lin-naturel",
        name: "Chèche en lin naturel",
        description: "Lin lavé ultra-léger, finitions à franges, teinture naturelle sans produits chimiques. 190 × 70 cm.",
        price: 79.9,
        categoryId: "c3",
        stock: 42,
        images: [cheche, cheche],
        rating: 4.4,
        featured: false,
        createdAt: "2025-12-05T09:00:00.000Z",
    },
    {
        id: "p8",
        slug: "huile-argan-bio",
        name: "Huile d'argan bio 100 ml",
        description: "Première pression à froid, certifiée biologique. Nourrit la peau, les cheveux et les ongles. Flacon ambré avec compte-gouttes.",
        price: 64,
        compareAtPrice: 79,
        categoryId: "c4",
        stock: 58,
        images: [argan, argan],
        rating: 4.8,
        featured: true,
        createdAt: "2025-11-22T09:00:00.000Z",
    },
];
export const customers = [
    {
        id: "u1",
        firstName: "Amine",
        lastName: "Ben Salah",
        email: "amine.bensalah@example.tn",
        phone: "+216 22 145 890",
        governorate: "Tunis",
        city: "El Menzah",
        ordersCount: 6,
        totalSpent: 2480.5,
        createdAt: "2025-09-14T09:00:00.000Z",
    },
    {
        id: "u2",
        firstName: "Rania",
        lastName: "Trabelsi",
        email: "rania.trabelsi@example.tn",
        phone: "+216 98 774 210",
        governorate: "Sousse",
        city: "Hammam Sousse",
        ordersCount: 3,
        totalSpent: 1129,
        createdAt: "2025-11-02T09:00:00.000Z",
    },
    {
        id: "u3",
        firstName: "Karim",
        lastName: "Jelassi",
        email: "karim.jelassi@example.tn",
        phone: "+216 55 320 118",
        governorate: "Sfax",
        city: "Sfax Ville",
        ordersCount: 2,
        totalSpent: 748.4,
        createdAt: "2026-01-19T09:00:00.000Z",
    },
    {
        id: "u4",
        firstName: "Sirine",
        lastName: "Mabrouk",
        email: "sirine.mabrouk@example.tn",
        phone: "+216 27 908 445",
        governorate: "Ariana",
        city: "Raoued",
        ordersCount: 8,
        totalSpent: 3910.75,
        createdAt: "2025-07-06T09:00:00.000Z",
    },
];
function getProduct(index) {
    const product = products[index];
    if (!product) {
        throw new Error(`Missing mock product at index ${index}`);
    }
    return product;
}
function item(product, quantity) {
    return {
        productId: product.id,
        name: product.name,
        image: product.images[0] ?? '',
        unitPrice: product.price,
        quantity,
    };
}
export const orders = [
    {
        id: "o1",
        reference: "CMD-2026-1041",
        customerId: "u1",
        address: {
            firstName: "Amine",
            lastName: "Ben Salah",
            phone: "+216 22 145 890",
            email: "amine.bensalah@example.tn",
            governorate: "Tunis",
            city: "El Menzah",
            locality: "El Menzah 5",
            postalCode: "1004",
            addressLine1: "12 rue des Jasmins",
            addressLine2: "Étage 2, appartement 4",
        },
        items: [item(getProduct(0), 1), item(getProduct(7), 2)],
        subtotal: 557.9,
        shippingFee: 8,
        total: 565.9,
        status: "SHIPMENT_CREATED",
        paymentMethod: "COD",
        abm: {
            trackingNumber: "ABM784512369",
            barcode: "784512369TN",
            positionCode: "TUN-04",
            hubName: "Hub Tunis Nord",
            createdAt: "2026-07-24T10:12:00.000Z",
            lastSyncAt: "2026-07-27T08:40:00.000Z",
        },
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-23T18:04:00.000Z" },
            { status: "VALIDATED", label: "Commande validée", at: "2026-07-24T09:20:00.000Z" },
            { status: "ABM_PROCESSING", label: "Transmission au transporteur", at: "2026-07-24T09:55:00.000Z" },
            { status: "SHIPMENT_CREATED", label: "Colis pris en charge", at: "2026-07-24T10:12:00.000Z", note: "Hub Tunis Nord" },
        ],
        createdAt: "2026-07-23T18:04:00.000Z",
    },
    {
        id: "o2",
        reference: "CMD-2026-1042",
        customerId: "u2",
        address: {
            firstName: "Rania",
            lastName: "Trabelsi",
            phone: "+216 98 774 210",
            email: "rania.trabelsi@example.tn",
            governorate: "Sousse",
            city: "Hammam Sousse",
            locality: "Kantaoui",
            postalCode: "4011",
            addressLine1: "Résidence Les Palmiers, bloc C",
        },
        items: [item(getProduct(4), 1)],
        subtotal: 890,
        shippingFee: 0,
        total: 890,
        status: "PENDING",
        paymentMethod: "COD",
        abm: {},
        timeline: [{ status: "PENDING", label: "Commande reçue", at: "2026-07-27T11:30:00.000Z" }],
        createdAt: "2026-07-27T11:30:00.000Z",
    },
    {
        id: "o3",
        reference: "CMD-2026-1043",
        customerId: "u3",
        address: {
            firstName: "Karim",
            lastName: "Jelassi",
            phone: "+216 55 320 118",
            email: "karim.jelassi@example.tn",
            governorate: "Sfax",
            city: "Sfax Ville",
            locality: "Route Tunis",
            postalCode: "3000",
            addressLine1: "Km 4, immeuble Nour",
        },
        items: [item(getProduct(1), 1), item(getProduct(6), 1)],
        subtotal: 698.9,
        shippingFee: 8,
        total: 706.9,
        status: "ABM_ERROR",
        paymentMethod: "COD",
        abm: {
            positionCode: "SFA-02",
            hubName: "Hub Sfax",
            lastSyncAt: "2026-07-26T15:02:00.000Z",
            errorCode: "ABM-422",
            errorMessage: "Localité non desservie par la position sélectionnée.",
        },
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-25T14:10:00.000Z" },
            { status: "VALIDATED", label: "Commande validée", at: "2026-07-26T09:00:00.000Z" },
            { status: "ABM_PROCESSING", label: "Transmission au transporteur", at: "2026-07-26T14:58:00.000Z" },
            { status: "ABM_ERROR", label: "Échec de création d'expédition", at: "2026-07-26T15:02:00.000Z", note: "ABM-422" },
        ],
        createdAt: "2026-07-25T14:10:00.000Z",
    },
    {
        id: "o4",
        reference: "CMD-2026-1044",
        customerId: "u4",
        address: {
            firstName: "Sirine",
            lastName: "Mabrouk",
            phone: "+216 27 908 445",
            email: "sirine.mabrouk@example.tn",
            governorate: "Ariana",
            city: "Raoued",
            locality: "Chotrana",
            postalCode: "2056",
            addressLine1: "24 avenue de l'Environnement",
        },
        items: [item(getProduct(3), 2)],
        subtotal: 518,
        shippingFee: 0,
        total: 518,
        status: "VALIDATED",
        paymentMethod: "COD",
        abm: { positionCode: "ARI-01", hubName: "Hub Ariana" },
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-26T20:41:00.000Z" },
            { status: "VALIDATED", label: "Commande validée", at: "2026-07-27T08:05:00.000Z" },
        ],
        createdAt: "2026-07-26T20:41:00.000Z",
    },
    {
        id: "o5",
        reference: "CMD-2026-1045",
        customerId: "u1",
        address: {
            firstName: "Amine",
            lastName: "Ben Salah",
            phone: "+216 22 145 890",
            email: "amine.bensalah@example.tn",
            governorate: "Tunis",
            city: "Tunis Centre",
            locality: "Lafayette",
            postalCode: "1000",
            addressLine1: "5 rue de Marseille",
        },
        items: [item(getProduct(2), 1)],
        subtotal: 189.5,
        shippingFee: 8,
        total: 197.5,
        status: "REJECTED",
        paymentMethod: "COD",
        rejectionReason: "Client injoignable après trois tentatives d'appel.",
        abm: {},
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-20T12:22:00.000Z" },
            { status: "REJECTED", label: "Commande rejetée", at: "2026-07-21T10:00:00.000Z", note: "Client injoignable" },
        ],
        createdAt: "2026-07-20T12:22:00.000Z",
    },
    {
        id: "o6",
        reference: "CMD-2026-1046",
        customerId: "u2",
        address: {
            firstName: "Rania",
            lastName: "Trabelsi",
            phone: "+216 98 774 210",
            email: "rania.trabelsi@example.tn",
            governorate: "Sousse",
            city: "Sousse Médina",
            locality: "Khezama",
            postalCode: "4000",
            addressLine1: "18 rue Ibn Khaldoun",
        },
        items: [item(getProduct(7), 3)],
        subtotal: 192,
        shippingFee: 8,
        total: 200,
        status: "ABM_PROCESSING",
        paymentMethod: "COD",
        abm: { positionCode: "SOU-03", hubName: "Hub Sousse", lastSyncAt: "2026-07-28T07:15:00.000Z" },
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-27T17:45:00.000Z" },
            { status: "VALIDATED", label: "Commande validée", at: "2026-07-28T07:02:00.000Z" },
            { status: "ABM_PROCESSING", label: "Transmission au transporteur", at: "2026-07-28T07:15:00.000Z" },
        ],
        createdAt: "2026-07-27T17:45:00.000Z",
    },
    {
        id: "o7",
        reference: "CMD-2026-1047",
        customerId: "u4",
        address: {
            firstName: "Sirine",
            lastName: "Mabrouk",
            phone: "+216 27 908 445",
            email: "sirine.mabrouk@example.tn",
            governorate: "Ariana",
            city: "Ariana Ville",
            locality: "Borj Louzir",
            postalCode: "2080",
            addressLine1: "3 impasse des Oliviers",
        },
        items: [item(getProduct(5), 1)],
        subtotal: 349,
        shippingFee: 8,
        total: 357,
        status: "CANCELLED",
        paymentMethod: "COD",
        abm: {},
        timeline: [
            { status: "PENDING", label: "Commande reçue", at: "2026-07-18T09:12:00.000Z" },
            { status: "CANCELLED", label: "Annulée par le client", at: "2026-07-18T18:30:00.000Z" },
        ],
        createdAt: "2026-07-18T09:12:00.000Z",
    },
];
export const abmPositions = [
    { id: "a1", code: "TUN-04", name: "Hub Tunis Nord", governorate: "Tunis", city: "El Menzah", capacity: 800, used: 512, status: "ACTIVE" },
    { id: "a2", code: "ARI-01", name: "Hub Ariana", governorate: "Ariana", city: "Ariana Ville", capacity: 600, used: 574, status: "SATURATED" },
    { id: "a3", code: "SOU-03", name: "Hub Sousse", governorate: "Sousse", city: "Sousse Médina", capacity: 500, used: 218, status: "ACTIVE" },
    { id: "a4", code: "SFA-02", name: "Hub Sfax", governorate: "Sfax", city: "Sfax Ville", capacity: 450, used: 0, status: "OFFLINE" },
    { id: "a5", code: "NAB-01", name: "Hub Nabeul", governorate: "Nabeul", city: "Hammamet", capacity: 350, used: 143, status: "ACTIVE" },
];
export const auditLogs = [
    { id: "l1", at: "2026-07-28T07:15:00.000Z", actor: "admin@store.tn", action: "ORDER_VALIDATED", target: "CMD-2026-1046", detail: "Validation manuelle puis envoi ABM", level: "INFO" },
    { id: "l2", at: "2026-07-26T15:02:00.000Z", actor: "system", action: "ABM_SHIPMENT_FAILED", target: "CMD-2026-1043", detail: "ABM-422 : localité non desservie", level: "ERROR" },
    { id: "l3", at: "2026-07-26T09:00:00.000Z", actor: "admin@store.tn", action: "ORDER_VALIDATED", target: "CMD-2026-1043", detail: "Validation manuelle", level: "INFO" },
    { id: "l4", at: "2026-07-25T16:40:00.000Z", actor: "admin@store.tn", action: "PRODUCT_UPDATED", target: "Enceinte Bluetooth Mira", detail: "Stock ajusté de 9 à 3", level: "WARNING" },
    { id: "l5", at: "2026-07-24T10:12:00.000Z", actor: "system", action: "ABM_SHIPMENT_CREATED", target: "CMD-2026-1041", detail: "Suivi ABM784512369", level: "INFO" },
    { id: "l6", at: "2026-07-21T10:00:00.000Z", actor: "admin@store.tn", action: "ORDER_REJECTED", target: "CMD-2026-1045", detail: "Client injoignable", level: "WARNING" },
];
export const settings = {
    storeName: "Dar Souk",
    supportEmail: "contact@darsouk.tn",
    supportPhone: "+216 71 000 000",
    shippingFee: 8,
    freeShippingThreshold: 400,
    codEnabled: true,
    abmEnabled: true,
    abmAccountLabel: "DARSOUK-PRO",
    abmEnvironment: "production",
    abmAutoCreateShipment: true,
};
