/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as CommandeRouteImport } from './routes/commande';
import { Route as CompteCommandesOrderIdRouteImport } from './routes/compte.commandes.$orderId';
import { Route as CompteCommandesIndexRouteImport } from './routes/compte.commandes.index';
import { Route as CompteIndexRouteImport } from './routes/compte.index';
import { Route as ConnexionRouteImport } from './routes/connexion';
import { Route as FavorisRouteImport } from './routes/favoris';
import { Route as IndexRouteImport } from './routes/index';
import { Route as InscriptionRouteImport } from './routes/inscription';
import { Route as PanierRouteImport } from './routes/panier';
import { Route as ProduitsProductIdRouteImport } from './routes/produits.$productId';
import { Route as ProduitsIndexRouteImport } from './routes/produits.index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index';
import { Route as AdminPositionsNouvelleRouteImport } from './routes/admin.positions.nouvelle';
import { Route as AdminPositionsIndexRouteImport } from './routes/admin.positions.index';
import { Route as AdminPositionsPositionIdRouteImport } from './routes/admin.positions.$positionId';
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const CommandeRoute = CommandeRouteImport.update({
    id: '/commande',
    path: '/commande',
    getParentRoute: () => rootRouteImport,
});
const CompteCommandesOrderIdRoute = CompteCommandesOrderIdRouteImport.update({
    id: '/compte/commandes/$orderId',
    path: '/compte/commandes/$orderId',
    getParentRoute: () => rootRouteImport,
});
const CompteCommandesIndexRoute = CompteCommandesIndexRouteImport.update({
    id: '/compte/commandes/',
    path: '/compte/commandes/',
    getParentRoute: () => rootRouteImport,
});
const CompteIndexRoute = CompteIndexRouteImport.update({
    id: '/compte/',
    path: '/compte/',
    getParentRoute: () => rootRouteImport,
});
const ConnexionRoute = ConnexionRouteImport.update({
    id: '/connexion',
    path: '/connexion',
    getParentRoute: () => rootRouteImport,
});
const FavorisRoute = FavorisRouteImport.update({
    id: '/favoris',
    path: '/favoris',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const InscriptionRoute = InscriptionRouteImport.update({
    id: '/inscription',
    path: '/inscription',
    getParentRoute: () => rootRouteImport,
});
const PanierRoute = PanierRouteImport.update({
    id: '/panier',
    path: '/panier',
    getParentRoute: () => rootRouteImport,
});
const ProduitsProductIdRoute = ProduitsProductIdRouteImport.update({
    id: '/produits/$productId',
    path: '/produits/$productId',
    getParentRoute: () => rootRouteImport,
});
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRoute,
});
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AdminRoute,
});
const AdminPositionsNouvelleRoute = AdminPositionsNouvelleRouteImport.update({
    id: '/positions/nouvelle',
    path: '/positions/nouvelle',
    getParentRoute: () => AdminRoute,
});
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
    id: '/positions/',
    path: '/positions/',
    getParentRoute: () => AdminRoute,
});
const AdminPositionsPositionIdRoute = AdminPositionsPositionIdRouteImport.update({
    id: '/positions/$positionId',
    path: '/positions/$positionId',
    getParentRoute: () => AdminRoute,
});
const AdminRouteChildren = {
    AdminIndexRoute,
    AdminCommandesIndexRoute,
    AdminPositionsNouvelleRoute,
    AdminPositionsIndexRoute,
    AdminPositionsPositionIdRoute,
};
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);
const rootRouteChildren = {
    IndexRoute,
    AdminRoute: AdminRouteWithChildren,
    CommandeRoute,
    CompteCommandesOrderIdRoute,
    CompteCommandesIndexRoute,
    CompteIndexRoute,
    ConnexionRoute,
    FavorisRoute,
    InscriptionRoute,
    PanierRoute,
    ProduitsProductIdRoute,
    ProduitsIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
