/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as CommandeRouteImport } from './routes/commande';
import { Route as CompteCommandesOrderIdRouteImport } from './routes/compte.commandes.$orderId';
import { Route as CompteCommandesIndexRouteImport } from './routes/compte.commandes.index';
import { Route as CompteIndexRouteImport } from './routes/compte.index';
import { Route as ConnexionRouteImport } from './routes/connexion';
import { Route as FavorisRouteImport } from './routes/favoris';
import { Route as IndexRouteImport } from './routes/index';
import { Route as InscriptionRouteImport } from './routes/inscription';
import { Route as PanierRouteImport } from './routes/panier';
import { Route as ProduitsProductIdRouteImport } from './routes/produits.$productId';
import { Route as ProduitsIndexRouteImport } from './routes/produits.index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index';
import { Route as AdminPositionsNouvelleRouteImport } from './routes/admin.positions.nouvelle';
import { Route as AdminPositionsIndexRouteImport } from './routes/admin.positions.index';
import { Route as AdminPositionsPositionIdRouteImport } from './routes/admin.positions.$positionId';

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any);
const CompteCommandesOrderIdRoute = CompteCommandesOrderIdRouteImport.update({
  id: '/compte/commandes/$orderId',
  path: '/compte/commandes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any);
const CompteCommandesIndexRoute = CompteCommandesIndexRouteImport.update({
  id: '/compte/commandes/',
  path: '/compte/commandes/',
  getParentRoute: () => rootRouteImport,
} as any);
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => rootRouteImport,
} as any);
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any);
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any);
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any);
const ProduitsProductIdRoute = ProduitsProductIdRouteImport.update({
  id: '/produits/$productId',
  path: '/produits/$productId',
  getParentRoute: () => rootRouteImport,
} as any);
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any);
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AdminRoute,
} as any);
const AdminPositionsNouvelleRoute = AdminPositionsNouvelleRouteImport.update({
  id: '/positions/nouvelle',
  path: '/positions/nouvelle',
  getParentRoute: () => AdminRoute,
} as any);
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AdminRoute,
} as any);
const AdminPositionsPositionIdRoute = AdminPositionsPositionIdRouteImport.update({
  id: '/positions/$positionId',
  path: '/positions/$positionId',
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteWithChildren;
  '/commande': typeof CommandeRoute;
  '/compte/': typeof CompteIndexRoute;
  '/compte/commandes/': typeof CompteCommandesIndexRoute;
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute;
  '/connexion': typeof ConnexionRoute;
  '/favoris': typeof FavorisRoute;
  '/inscription': typeof InscriptionRoute;
  '/panier': typeof PanierRoute;
  '/produits/': typeof ProduitsIndexRoute;
  '/produits/$productId': typeof ProduitsProductIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/admin/commandes/': typeof AdminCommandesIndexRoute;
  '/admin/positions/nouvelle': typeof AdminPositionsNouvelleRoute;
  '/admin/positions/': typeof AdminPositionsIndexRoute;
  '/admin/positions/$positionId': typeof AdminPositionsPositionIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/admin': typeof AdminIndexRoute;
  '/admin/commandes': typeof AdminCommandesIndexRoute;
  '/admin/positions/nouvelle': typeof AdminPositionsNouvelleRoute;
  '/admin/positions': typeof AdminPositionsIndexRoute;
  '/admin/positions/$positionId': typeof AdminPositionsPositionIdRoute;
  '/commande': typeof CommandeRoute;
  '/compte': typeof CompteIndexRoute;
  '/compte/commandes': typeof CompteCommandesIndexRoute;
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute;
  '/connexion': typeof ConnexionRoute;
  '/favoris': typeof FavorisRoute;
  '/inscription': typeof InscriptionRoute;
  '/panier': typeof PanierRoute;
  '/produits': typeof ProduitsIndexRoute;
  '/produits/$productId': typeof ProduitsProductIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteWithChildren;
  '/commande': typeof CommandeRoute;
  '/compte/': typeof CompteIndexRoute;
  '/compte/commandes/': typeof CompteCommandesIndexRoute;
  '/compte/commandes/$orderId': typeof CompteCommandesOrderIdRoute;
  '/connexion': typeof ConnexionRoute;
  '/favoris': typeof FavorisRoute;
  '/inscription': typeof InscriptionRoute;
  '/panier': typeof PanierRoute;
  '/produits/': typeof ProduitsIndexRoute;
  '/produits/$productId': typeof ProduitsProductIdRoute;
  '/admin/': typeof AdminIndexRoute;
  '/admin/commandes/': typeof AdminCommandesIndexRoute;
  '/admin/positions/nouvelle': typeof AdminPositionsNouvelleRoute;
  '/admin/positions/': typeof AdminPositionsIndexRoute;
  '/admin/positions/$positionId': typeof AdminPositionsPositionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/commande'
    | '/compte/'
    | '/compte/commandes/'
    | '/compte/commandes/$orderId'
    | '/connexion'
    | '/favoris'
    | '/inscription'
    | '/panier'
    | '/produits/'
    | '/produits/$productId'
    | '/admin/'
    | '/admin/commandes/'
    | '/admin/positions/nouvelle'
    | '/admin/positions/'
    | '/admin/positions/$positionId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/admin'
    | '/admin/commandes'
    | '/admin/positions/nouvelle'
    | '/admin/positions'
    | '/admin/positions/$positionId'
    | '/commande'
    | '/compte'
    | '/compte/commandes'
    | '/compte/commandes/$orderId'
    | '/connexion'
    | '/favoris'
    | '/inscription'
    | '/panier'
    | '/produits'
    | '/produits/$productId';
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/commande'
    | '/compte/'
    | '/compte/commandes/'
    | '/compte/commandes/$orderId'
    | '/connexion'
    | '/favoris'
    | '/inscription'
    | '/panier'
    | '/produits/'
    | '/produits/$productId'
    | '/admin/'
    | '/admin/commandes/'
    | '/admin/positions/nouvelle'
    | '/admin/positions/'
    | '/admin/positions/$positionId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  CommandeRoute: typeof CommandeRoute;
  CompteCommandesOrderIdRoute: typeof CompteCommandesOrderIdRoute;
  CompteCommandesIndexRoute: typeof CompteCommandesIndexRoute;
  CompteIndexRoute: typeof CompteIndexRoute;
  ConnexionRoute: typeof ConnexionRoute;
  FavorisRoute: typeof FavorisRoute;
  InscriptionRoute: typeof InscriptionRoute;
  PanierRoute: typeof PanierRoute;
  ProduitsProductIdRoute: typeof ProduitsProductIdRoute;
  ProduitsIndexRoute: typeof ProduitsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/commande': {
      id: '/commande';
      path: '/commande';
      fullPath: '/commande';
      preLoaderRoute: typeof CommandeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/compte/commandes/$orderId': {
      id: '/compte/commandes/$orderId';
      path: '/compte/commandes/$orderId';
      fullPath: '/compte/commandes/$orderId';
      preLoaderRoute: typeof CompteCommandesOrderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/compte/commandes/': {
      id: '/compte/commandes/';
      path: '/compte/commandes';
      fullPath: '/compte/commandes/';
      preLoaderRoute: typeof CompteCommandesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/compte/': {
      id: '/compte/';
      path: '/compte';
      fullPath: '/compte/';
      preLoaderRoute: typeof CompteIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/connexion': {
      id: '/connexion';
      path: '/connexion';
      fullPath: '/connexion';
      preLoaderRoute: typeof ConnexionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/favoris': {
      id: '/favoris';
      path: '/favoris';
      fullPath: '/favoris';
      preLoaderRoute: typeof FavorisRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/inscription': {
      id: '/inscription';
      path: '/inscription';
      fullPath: '/inscription';
      preLoaderRoute: typeof InscriptionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/panier': {
      id: '/panier';
      path: '/panier';
      fullPath: '/panier';
      preLoaderRoute: typeof PanierRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/produits/$productId': {
      id: '/produits/$productId';
      path: '/produits/$productId';
      fullPath: '/produits/$productId';
      preLoaderRoute: typeof ProduitsProductIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/produits/': {
      id: '/produits/';
      path: '/produits';
      fullPath: '/produits/';
      preLoaderRoute: typeof ProduitsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/commandes/': {
      id: '/commandes/';
      path: '/commandes/';
      fullPath: '/admin/commandes/';
      preLoaderRoute: typeof AdminCommandesIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/positions/nouvelle': {
      id: '/positions/nouvelle';
      path: '/positions/nouvelle';
      fullPath: '/admin/positions/nouvelle';
      preLoaderRoute: typeof AdminPositionsNouvelleRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/positions/': {
      id: '/positions/';
      path: '/positions/';
      fullPath: '/admin/positions/';
      preLoaderRoute: typeof AdminPositionsIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/positions/$positionId': {
      id: '/positions/$positionId';
      path: '/positions/$positionId';
      fullPath: '/admin/positions/$positionId';
      preLoaderRoute: typeof AdminPositionsPositionIdRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminCommandesIndexRoute: typeof AdminCommandesIndexRoute;
  AdminPositionsNouvelleRoute: typeof AdminPositionsNouvelleRoute;
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute;
  AdminPositionsPositionIdRoute: typeof AdminPositionsPositionIdRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute,
  AdminCommandesIndexRoute,
  AdminPositionsNouvelleRoute,
  AdminPositionsIndexRoute,
  AdminPositionsPositionIdRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommandeRoute,
  CompteCommandesOrderIdRoute,
  CompteCommandesIndexRoute,
  CompteIndexRoute,
  ConnexionRoute,
  FavorisRoute,
  InscriptionRoute,
  PanierRoute,
  ProduitsProductIdRoute,
  ProduitsIndexRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
