import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "@tanstack/react-router";
import { ShoppingBag, Trash2 } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { QuantitySelector } from "./QuantitySelector";
import { EmptyState, LoadingSkeleton } from "@/components/common/states";
import { formatTND } from "@/lib/format";
import { useStore } from "@/features/store/store-context";
import { useCartDetails } from "@/features/store/use-cart-details";
export function CartDrawer() {
    const { cartOpen, setCartOpen, setQuantity, removeFromCart } = useStore();
    const { lines, subtotal, shippingFee, total, isLoading } = useCartDetails();
    return (_jsx(Sheet, { open: cartOpen, onOpenChange: setCartOpen, children: _jsxs(SheetContent, { className: "flex w-full flex-col gap-0 sm:max-w-md", children: [_jsxs(SheetHeader, { children: [_jsx(SheetTitle, { children: "Votre panier" }), _jsx(SheetDescription, { children: lines.length > 0 ? `${lines.length} article(s) prêt(s) à être livré(s)` : "Votre panier est vide" })] }), _jsx("div", { className: "flex-1 overflow-y-auto px-4", children: isLoading ? (_jsx(LoadingSkeleton, { count: 3 })) : lines.length === 0 ? (_jsx(EmptyState, { title: "Panier vide", description: "Parcourez le catalogue et ajoutez vos articles pr\u00E9f\u00E9r\u00E9s.", icon: ShoppingBag, action: _jsx(Button, { asChild: true, onClick: () => setCartOpen(false), children: _jsx(Link, { to: "/produits", children: "Voir le catalogue" }) }) })) : (_jsx("ul", { className: "space-y-4 py-2", children: lines.map(({ product, quantity }) => (_jsxs("li", { className: "flex gap-3", children: [_jsx("img", { src: product.images[0], alt: product.name, loading: "lazy", width: 900, height: 900, className: "size-20 shrink-0 rounded-xl object-cover" }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("p", { className: "truncate text-sm font-semibold", children: product.name }), _jsx("p", { className: "text-sm text-muted-foreground", children: formatTND(product.price) }), _jsxs("div", { className: "mt-2 flex items-center gap-2", children: [_jsx(QuantitySelector, { value: quantity, max: Math.max(1, product.stock), onChange: (value) => setQuantity(product.id, value) }), _jsx(Button, { variant: "ghost", size: "icon", "aria-label": `Retirer ${product.name}`, onClick: () => removeFromCart(product.id), children: _jsx(Trash2, { className: "size-4" }) })] })] })] }, product.id))) })) }), lines.length > 0 ? (_jsxs(SheetFooter, { className: "gap-3 border-t border-border", children: [_jsxs("div", { className: "space-y-1.5 text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-muted-foreground", children: "Sous-total" }), _jsx("span", { className: "font-medium", children: formatTND(subtotal) })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-muted-foreground", children: "Livraison" }), _jsx("span", { className: "font-medium", children: shippingFee === 0 ? "Offerte" : formatTND(shippingFee) })] }), _jsx(Separator, {}), _jsxs("div", { className: "flex justify-between text-base font-semibold", children: [_jsx("span", { children: "Total" }), _jsx("span", { children: formatTND(total) })] })] }), _jsx(Button, { asChild: true, size: "lg", onClick: () => setCartOpen(false), children: _jsx(Link, { to: "/commande", children: "Passer la commande" }) }), _jsx(Button, { asChild: true, variant: "outline", onClick: () => setCartOpen(false), children: _jsx(Link, { to: "/panier", children: "Voir le panier" }) })] })) : null] }) }));
}
