import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from '@/components/ui/select';
export function PositionsPagination({ page, pageSize, totalItems, totalPages, onPageChange, onPageSizeChange, }) {
    const first = totalItems === 0 ? 0 : (page - 1) * pageSize + 1;
    const last = Math.min(page * pageSize, totalItems);
    const pages = Array.from({ length: totalPages }, (_, i) => i + 1).filter((p) => p === 1 || p === totalPages || Math.abs(p - page) <= 1);
    return (_jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3 text-sm text-muted-foreground", children: [_jsxs("span", { children: ["Affichage de ", first, " \u00E0 ", last, " sur ", totalItems, " positions"] }), _jsxs(Select, { value: String(pageSize), onValueChange: (v) => onPageSizeChange(Number(v)), children: [_jsx(SelectTrigger, { className: "h-9 w-[110px]", "aria-label": "Positions par page", children: _jsx(SelectValue, {}) }), _jsx(SelectContent, { children: [10, 20, 50].map((size) => (_jsxs(SelectItem, { value: String(size), children: [size, " / page"] }, size))) })] })] }), _jsxs("nav", { className: "flex items-center gap-1", "aria-label": "Pagination", children: [_jsx(Button, { variant: "outline", size: "icon", "aria-label": "Page pr\u00E9c\u00E9dente", disabled: page <= 1, onClick: () => onPageChange(page - 1), children: _jsx(ChevronLeft, { className: "size-4" }) }), pages.map((p, index) => (_jsxs("span", { className: "flex items-center", children: [index > 0 && p - (pages[index - 1] ?? p) > 1 ? (_jsx("span", { className: "px-1 text-muted-foreground", children: "\u2026" })) : null, _jsx(Button, { variant: p === page ? 'default' : 'ghost', size: "icon", "aria-label": `Page ${p}`, "aria-current": p === page ? 'page' : undefined, onClick: () => onPageChange(p), children: p })] }, p))), _jsx(Button, { variant: "outline", size: "icon", "aria-label": "Page suivante", disabled: page >= totalPages, onClick: () => onPageChange(page + 1), children: _jsx(ChevronRight, { className: "size-4" }) })] })] }));
}
