import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronDown, ChevronRight, MapPin, Package, Phone } from 'lucide-react';
import { formatTND } from '@/lib/format';
import { cn } from '@/lib/utils';
import { formatShortDate, formatShortTime } from '../lib/position-formatters';
import { PositionActionsMenu } from './PositionActionsMenu';
import { PositionExpandedDetails } from './PositionExpandedDetails';
import { PositionStatusBadge } from './PositionStatusBadge';
export function PositionMobileCard({ position: p, expanded, onToggle, onCopy, onView, onEdit, onDelete, }) {
    return (_jsxs("article", { className: cn('surface-card p-4', expanded && 'ring-1 ring-primary/20'), children: [_jsxs("div", { className: "grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3", children: [_jsxs("button", { type: "button", onClick: onToggle, "aria-expanded": expanded, className: "min-w-0 rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [expanded ? (_jsx(ChevronDown, { className: "size-4 shrink-0 text-muted-foreground" })) : (_jsx(ChevronRight, { className: "size-4 shrink-0 text-muted-foreground" })), _jsx("span", { className: "truncate font-semibold tabular-nums", children: p.barcode })] }), _jsx("p", { className: "mt-0.5 truncate pl-5 text-xs text-muted-foreground", children: p.reference })] }), _jsx(PositionActionsMenu, { position: p, onView: onView, onEdit: onEdit, onCopy: () => onCopy(p.barcode), onDelete: onDelete })] }), _jsxs("div", { className: "mt-3 flex flex-wrap items-center gap-2", children: [_jsx(PositionStatusBadge, { statusCategory: p.statusCategory, statusLabel: p.statusLabel }), _jsx("span", { className: "inline-flex rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary", children: p.service }), _jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-xs font-medium", children: [_jsx(Package, { className: "size-3.5", "aria-hidden": true }), p.pieces] })] }), _jsxs("dl", { className: "mt-3 space-y-1.5 text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Phone, { className: "size-4 shrink-0 text-muted-foreground", "aria-hidden": true }), _jsxs("span", { className: "min-w-0 truncate", children: [p.recipient.fullName, " \u00B7 ", p.recipient.phone] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "size-4 shrink-0 text-muted-foreground", "aria-hidden": true }), _jsxs("span", { className: "min-w-0 truncate", children: [p.destination.governorate, " \u00B7 ", p.destination.city] })] })] }), _jsxs("div", { className: "mt-3 flex items-center justify-between border-t border-border pt-3", children: [_jsxs("span", { className: "text-xs text-muted-foreground", children: [formatShortDate(p.createdAt), " \u00B7 ", formatShortTime(p.createdAt)] }), _jsx("span", { className: "text-sm font-semibold tabular-nums", children: formatTND(p.codAmount) })] }), expanded ? (_jsx("div", { className: "mt-3", children: _jsx(PositionExpandedDetails, { position: p, onView: onView, onEdit: onEdit, onDelete: onDelete }) })) : null] }));
}
