import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, Barcode, Download, Eye, MoreHorizontal, Pencil, Printer, RefreshCw, Trash2 } from 'lucide-react';
import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger, } from '@/components/ui/dropdown-menu';
import { PositionStatusBadge } from '@/features/admin/abm-positions-list';
import { cn } from '@/lib/utils';
const isActionLoading = (current, action) => current === action;
export function PositionDetailHeader({ position, backSearch, refreshing, onRefresh, onDelete, printLoadingAction, onPrint, }) {
    const printBusy = printLoadingAction !== null;
    return (_jsxs("div", { className: "surface-card space-y-5 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsx(Button, { asChild: true, variant: "ghost", className: "-ml-2", children: _jsxs(Link, { to: "/admin/positions", ...(backSearch ? { search: backSearch } : {}), children: [_jsx(ArrowLeft, { className: "size-4" }), "Retour aux positions"] }) }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsxs(Button, { variant: "outline", onClick: onRefresh, disabled: refreshing, children: [_jsx(RefreshCw, { className: cn('size-4', refreshing && 'animate-spin') }), "Actualiser"] }), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs(Button, { variant: "outline", disabled: printBusy, children: [_jsx(Printer, { className: "size-4" }), "Imprimer"] }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-72", children: [_jsx(DropdownMenuLabel, { children: "Impression ABM" }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { disabled: printBusy || !position.permissions.canPrintNormal, onSelect: () => onPrint('preview-normal'), children: [_jsx(Eye, { className: "size-4" }), isActionLoading(printLoadingAction, 'preview-normal')
                                                        ? "Chargement de l'etiquette normale..."
                                                        : 'Previsualiser etiquette normale'] }), _jsxs(DropdownMenuItem, { disabled: printBusy || !position.permissions.canPrintNormal, onSelect: () => onPrint('pdf-normal'), children: [_jsx(Download, { className: "size-4" }), isActionLoading(printLoadingAction, 'pdf-normal')
                                                        ? 'Preparation du PDF normal...'
                                                        : 'Telecharger l\'etiquette normale PDF'] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { disabled: printBusy || !position.permissions.canPrintZebra, onSelect: () => onPrint('preview-zebra'), children: [_jsx(Barcode, { className: "size-4" }), isActionLoading(printLoadingAction, 'preview-zebra')
                                                        ? "Chargement de l'etiquette Zebra..."
                                                        : 'Previsualiser etiquette Zebra'] }), _jsxs(DropdownMenuItem, { disabled: printBusy || !position.permissions.canPrintZebra, onSelect: () => onPrint('pdf-zebra'), children: [_jsx(Download, { className: "size-4" }), isActionLoading(printLoadingAction, 'pdf-zebra')
                                                        ? 'Preparation du PDF Zebra...'
                                                        : 'Telecharger l\'etiquette Zebra PDF'] })] })] }), _jsxs(Button, { variant: "outline", disabled: true, children: [_jsx(Pencil, { className: "size-4" }), "Modifier - Bientot"] }), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { variant: "outline", size: "icon", "aria-label": "Plus d'actions", children: _jsx(MoreHorizontal, { className: "size-4" }) }) }), _jsx(DropdownMenuContent, { align: "end", className: "w-56", children: _jsxs(DropdownMenuItem, { disabled: !position.permissions.canDelete, onSelect: onDelete, className: "text-destructive focus:text-destructive", children: [_jsx(Trash2, { className: "size-4" }), "Supprimer"] }) })] })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-[0.22em] text-muted-foreground", children: "Detail de la position" }), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs("h1", { className: "font-display text-3xl font-semibold tracking-tight sm:text-4xl", children: ["Position ", position.barcode] }), _jsx(PositionStatusBadge, { statusCategory: position.status.category, statusLabel: position.status.label, className: "text-sm" })] }), _jsx("p", { className: "max-w-3xl text-sm text-muted-foreground sm:text-base", children: "Consultez les informations, le statut et l'historique complet de cette expedition." })] })] }));
}
